"""empty message

Revision ID: 219c15932869
Revises: None
Create Date: 2015-12-21 09:17:39.582655

"""

# revision identifiers, used by Alembic.
revision = '219c15932869'
down_revision = None

from alembic import op
import sqlalchemy as sa
from Application.models.UTCDateTime import UTCDateTime

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('dn', sa.String(length=255), nullable=True),
    sa.Column('zid', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('has_logged_in', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('zid')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_uploaded', UTCDateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=20), nullable=True),
    sa.Column('download_link', sa.String(length=255), nullable=True),
    sa.Column('website_link', sa.String(length=255), nullable=True),
    sa.Column('demo_link', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.zid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_followers',
    sa.Column('follower_id', sa.String(length=20), nullable=True),
    sa.Column('followee_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['user.zid'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.zid'], )
    )
    op.create_table('project_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_users_devs',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.zid'], )
    )
    op.create_table('project_users_stars',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.zid'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_users_stars')
    op.drop_table('project_users_devs')
    op.drop_table('project_image')
    op.drop_table('users_followers')
    op.drop_table('project')
    op.drop_table('user')
    ### end Alembic commands ###
