"""empty message

Revision ID: 5aadd6d59e8b
Revises: 2e633cd2015d
Create Date: 2015-12-20 07:17:48.445670

"""

# revision identifiers, used by Alembic.
revision = '5aadd6d59e8b'
down_revision = '2e633cd2015d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_logged_in', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_logged_in')
    ### end Alembic commands ###
